# Generated by Django 4.2.16 on 2026-05-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=80)),
                ('capacity_tons', models.IntegerField(default=1000)),
                ('used_tons', models.IntegerField(default=0)),
            ],
        ),
    ]
